### ISSUE TITLE
Is there exist any way how to make it enable and disable ?

### ISSUE THREAD

**Issue by Abdelsattar** [Ch4rl3x/revealswipe#11]
Hey,

Many thanks for the code it's really working great. 

I have a problem I wanna use it as a wrapper for the item and this item is used with multiple lists so not all of the list will have it, so I was asking if there exists a way of making it enable or disable it.

**Comment by ch4rl3x** [comment]
Hey. 
You can enable/disable the swipe with `enableSwipe`. As an alternative you can set `directions = emptySet()`. With empyt direction set.

In my opinion, the empty direction set works better.

**Comment by Abdelsattar** [comment]
Thanks that I wanted to do
