### ISSUE TITLE
Query: contribution

### ISSUE THREAD

**Issue by CiaranSloanRH** [Ch4rl3x/revealswipe#14]
Hi there 👋 

Love the library, its been really nice to work with. Wanted to ask about contributions and if you have some guidelines for that? There is a use case I have that is missing from the library:

Currently the hidden content can only be a maximum width of 50% of the container. This is problematic when using only 1 swipe direction and the hidden content is wider than 50% of the width. ([ref](https://github.com/ch4rl3x/RevealSwipe/blob/c30be0d2288933f3c41054b3eff11d4f1a274d3b/revealswipe/src/main/java/de/charlex/compose/RevealSwipe.kt#L221))

I'd be happy to submit a PR to fix this, if you'd be willing and can point me to some contribution guidelines :)

**Comment by ch4rl3x** [comment]
Hey. Feel free to submit a PR. At the moment, there are no contribution guidelines :)

**Comment by CiaranSloanRH** [comment]
cool thanks! PR [here](https://github.com/ch4rl3x/RevealSwipe/pull/15)
